### ISSUE TITLE
Database leak.

### ISSUE THREAD

**Issue by swoldbye** [swoldbye/SkibsLogApp#100]
The following line from "run" explains the problem:

W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.example.skibslogapp/databases/logbog.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

**Comment by maltebp** [comment]
Note to eslf: der skal bare kaldes '''.close()''' på database-objektet
